version: '3.4'

services:
  edifice-api:
    image: edifice-api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      POSTGRES_PASSWORD: example
    depends_on:
      - database
      - migration
    ports:
      - 3000:3000
    command: node src/app.js

  edifice-ui:
    image: edifice-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - edifice-api
    ports:
      - 8080:80
    command: nginx -g 'daemon off;'

  hasura:
    image: hasura/graphql-engine:latest.cli-migrations-v2
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:example@database:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    depends_on:
      - database
    ports:
      - 8081:8080

  migration:
    image: edifice
    build: .
    command: npm run db:migrate
    depends_on:
      - database

  database:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  graphite-statsd:
    image: graphiteapp/graphite-statsd
    ports:
      - 80:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:825/udp
      - 8126:8126

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
