apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: graphite-statsd
  name: graphite-statsd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: graphite-statsd
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: graphite-statsd
    spec:
      containers:
        - image: graphiteapp/graphite-statsd
          name: graphite-statsd
          ports:
            - containerPort: 80
            - containerPort: 2003
            - containerPort: 2004
            - containerPort: 2023
            - containerPort: 2024
            - containerPort: 825
              protocol: UDP
            - containerPort: 8126
          resources: {}
      restartPolicy: Always
status: {}
