apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-dep
  labels:
    app: edifice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edifice
  template:
    metadata:
      labels:
        app: edifice
    spec:
      containers:
      - name: database
        image: postgres:13.2-alpine
        env:
          - name: POSTGRES_PASSWORD
            value: example
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
      restartPolicy: Always