apiVersion: apps/v1
kind: Deployment
metadata:
  name: edifice-dep
  labels:
    app: edifice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edifice
  template:
    metadata:
      labels:
        app: edifice
    spec:
      containers:
      - name: edifice
        image: kashew1/edifice:latest
        env:
          - name: POSTGRES_PASSWORD
            value: example
          - name: NODE_ENV
            value: production
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ["node", "src/app.js"]
        ports:
        - containerPort: 3000